### ISSUE TITLE
deepchange /ltcc 训练

### ISSUE THREAD

**Issue by LinranQi** [Gpn-star/SCNet#10]
作者您好，我对这篇文章的工作很感兴趣。我在训练过程中遇到下面两个问题，希望可以得到您的帮助。

请问网络在deepchange数据集上训练时，代码超参数的设置只需要修改vcloss和partloss前的系数为0.01吗，此时我的训练结果只能达到44.7%，可能是什么原因导致的。

另一个问题是在ltcc上进行raw-black双流训练时，我得到的结果要比只使用raw单流的结果低，请问这个消融实验训练时应该怎么设置相关参数。

期待您的回复。

**Comment by Gpn-star** [comment]
1.除了损失函数权重与论文一致外，请确保和README.md中的环境设置一致（多卡并行训练，32×2=64）
2.实验时，是使用双流特征连接后的结果进行训练和预测。

**Comment by LinranQi** [comment]
> 1.除了损失函数权重与论文一致外，请确保和README.md中的环境设置一致（多卡并行训练，32×2=64） 2.实验时，是使用双流特征连接后的结果进行训练和预测。

好的，谢谢。对于ltcc上进行raw-black双流训练，我是在训练和测试时将raw和black特征拼接在一起进行预测和计算相似度排序的，但是最终双流的结果比单流换装情况下的top1值低了约10%，我是用单卡进行训练的，但单双卡训练应该不会影响指标增长或降低的趋势 。然后对于ltcc数据集上，只使用black流进行测试时最终结果也是要比raw的结果低很多，所以我想问是不是训练过程中还有哪些细节需要注意，因为我觉得环境应该不会影响最终结果增长或降低的趋势。

**Comment by Gpn-star** [comment]
代码是基于分布式训练编写的，在并行环境下能够取得更好的效果，因此建议使用多卡训练。你也可以参考 [https://github.com/guxinqian/Simple-CCReID/issues/8](https://github.com/guxinqian/Simple-CCReID/issues/8) 中作者的解释。我记得对于PRCC数据集，黑衣图像对性能的提升比较显著，LTCC数据集则相反，这可能是由于LTCC具有更加剧烈的光照和姿态变化以及遮挡现象，导致人体解析模型的效果不佳，从而影响黑衣图像的效果。在训练过程中可以根据不同数据集适当降低/提升衣着擦除流的权重。

**Comment by LinranQi** [comment]
> 代码是基于分布式训练编写的，在并行环境下能够取得更好的效果，因此建议使用多卡训练。你也可以参考 [guxinqian/Simple-CCReID#8](https://github.com/guxinqian/Simple-CCReID/issues/8) 中作者的解释。我记得对于PRCC数据集，黑衣图像对性能的提升比较显著，LTCC数据集则相反，这可能是由于LTCC具有更加剧烈的光照和姿态变化以及遮挡现象，导致人体解析模型的效果不佳，从而影响黑衣图像的效果。在训练过程中可以根据不同数据集适当降低/提升衣着擦除流的权重。

好的，谢谢。

**Comment by superzm1** [comment]
您好，有些问题想问一下您，请问您在PRCC数据上的复现结果如何，用了几张卡，具体修改了代码的哪些部分呢？

**Comment by hxy-499** [comment]
> 您好，有些问题想问一下您，请问您在PRCC数据上的复现结果如何，用了几张卡，具体修改了代码的哪些部分呢？

您好，请问您在复现PRCC数据集时，有遇到OSError: /home/bingxing2/home/scx6d0o/prcc/rgb/processed/092/B_cropped_rgb066_layer4_layer3_Cam_On_Image.png does not exist这个类似的问题吗

**Comment by cheese-jerry** [comment]
> 您好，有些问题想问一下您，请问您在PRCC数据上的复现结果如何，用了几张卡，具体修改了代码的哪些部分呢？

您好，请问还在研究变装行人重识别吗，方便留个联系方式交流吗

**Comment by cheese-jerry** [comment]
> > 您好，有些问题想问一下您，请问您在PRCC数据上的复现结果如何，用了几张卡，具体修改了代码的哪些部分呢？
> 
> 您好，请问您在复现PRCC数据集时，有遇到OSError: /home/bingxing2/home/scx6d0o/prcc/rgb/processed/092/B_cropped_rgb066_layer4_layer3_Cam_On_Image.png does not exist这个类似的问题吗

您好，请问还在研究变装行人重识别吗，方便留个联系方式交流吗
