### ISSUE TITLE
我无法复现达到论文的结果

### ISSUE THREAD

**Issue by lph001009** [Gpn-star/SCNet#11]
在LTCC数据集上我复现的结果：换衣设置下rank-1为37.2%，mAP为22.4%
![1](https://github.com/Gpn-star/SCNet/assets/74615696/73ae1049-326f-4a39-b785-6511cccae9d0)

**Comment by Gpn-star** [comment]
除了损失函数权重与论文一致外，请确保和README.md中的环境设置一致（多卡并行训练，32×2=64）
