### ISSUE TITLE
Why are my results reproduced on the prcc dataset lower than those presented in the paper

### ISSUE THREAD

**Issue by superzm1** [Gpn-star/SCNet#12]
Why are my results reproduced on the prcc dataset lower than those presented in the paper

**Comment by Gpn-star** [comment]
Please provide your specific implementation details, otherwise I am not sure whether your experimental environment is consistent with the requirements. In addition, please refer to my other answers, which may be helpful to you.

**Comment by superzm1** [comment]
I used the data set you provided, only modified the data set path, ltcc data set is acceptable, but prcc results are slightly different

**Comment by gf2020whj** [comment]
> Why are my results reproduced on the prcc dataset lower than those presented in the paper

Hello, may I ask if the result you reproduced on ltcc is much different from the original text? I used Torch 1.7.0 version, and the effect of running two 3090 cards is quite different from the author's. Can you tell me what your configuration environment is. Looking forward to your reply, thank you!
