### ISSUE TITLE
reimplemented results not matching paper results

### ISSUE THREAD

**Issue by QingzeYin** [Gpn-star/SCNet#4]
Dear author,

Thanks for sharing your code. I reimplemented your code without any changes, but the result is 52.6% of R-1 on the PRCC dataset.    I used two a100-40G GPUs and changed the two losses' lambda in Eq.5 to 0.1. I checked the code and made sure that is consistent with your experimental settings in the paper. Could you please have a look at the GitHub code? Maybe there is some other reason leading to the weak results. Look forward to your reply.

**Comment by yc-19991223** [comment]
请问你用的pytorch和python版本是和作者的一样嘛？

**Comment by yc-19991223** [comment]
Are the versions of torch and python you are using the same as the author's in README.md?

**Comment by QingzeYin** [comment]
> Are the versions of torch and python you are using the same as the author's in README.md?

Yes! I set the experimental environment followed by README.md exactly.

**Comment by yc-19991223** [comment]
?
***@***.***



&nbsp;
您好，可以请教您一个问题吗？您使用的pytorch1.6.0版本，在运行的时候，在train.py中parsing_results = Resize(parsing_results)
这一行一直报错，报错信息如附件所示，大致意思就是不能用Resize函数对tensor进行调整大小，但是我换到pytorch2.0.0版本中就没有这个问题！想请问您是怎么解决的？如果您没有这个问题，那应该就是我的原因。期待您的回复，谢谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gpn-star/SCNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 晚上7:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gpn-star/SCNet] reimplemented results not matching paper results (Issue #4)





  
Are the versions of torch and python you are using the same as the author's in README.md?
  
Yes! I set the experimental environment followed by README.md exactly.

**Comment by Gpn-star** [comment]
Thanks for your question. I will carefully check the errors in the code uploaded to GitHub, please wait patiently for a while.

**Comment by QingzeYin** [comment]
> Thanks for your question. I will carefully check the errors in the code uploaded to GitHub, please wait patiently for a while.

Thanks for your reply! !
